DROP TABLE BOOKS;

CREATE TABLE BOOKS (BOOKID INT, 
TITLE VARCHAR(100), 
AUTHOR VARCHAR(100),
AVERAGE_RATING VARCHAR(100), 
ISBN VARCHAR(100), 
ISBN13 VARCHAR(100), 
LANGUAGE_CODE VARCHAR(100), 
NUM_PAGES INT, 
RATINGS_COUNT INT,
TEXT_REVIEWS_COUNT INT, 
PUBLICATION_DATE VARCHAR(100), 
PUBLISHER VARCHAR(100), PRIMARY KEY(BOOKID)) AS SELECT * FROM CSVREAD('/Users/lakshmipalchuri/Desktop/bookDB.csv');
